# Generated by Django 5.1.1 on 2024-09-11 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('task_object', models.IntegerField()),
                ('status', models.IntegerField(default=100)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now_add=datetime.datetime(2024, 9, 11, 11, 29, 5, 899634, tzinfo=datetime.timezone.utc))),
                ('date_closing', models.DateField(blank=True, null=True)),
                ('time_closing', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
