"""empty message

Revision ID: 342d9133e146
Revises: 
Create Date: 2024-09-07 19:42:13.137594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342d9133e146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('e_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ep_name', sa.String(length=150), nullable=False),
    sa.Column('ep_duration', sa.Integer(), nullable=False),
    sa.Column('ep_price', sa.Integer(), nullable=False),
    sa.Column('ep_createDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('e_products')
    # ### end Alembic commands ###
