# Generated by Django 5.1.1 on 2024-09-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.IntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=90)),
                ('short_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id_state', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hw7_app.department')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hw7_app.state')),
            ],
        ),
    ]
