services:
  db:
     image: postgres:16
     container_name: flask_db
     hostname: flask_db
     environment:
       POSTGRES_DB: flask_db
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       PGDATA: "/var/lib/postgresql/data/pgdata"
     volumes:
       - /home/davydov/Documents/Docker/LocalVolume:/var/docker_vol1
       - ./db_data:/var/lib/postgresql/data
     healthcheck:
        test: ["CMD-SHELL", "pg_isready -d flask_db -U postgres"]
        interval: 5s
        timeout: 3s
        retries: 5
  
  app:
    container_name: flask_app
    hostname: flask_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - FLASK_APP=main.py
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/flask_db
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy